### ISSUE TITLE
Pyxel doesn't work with the latest Maturin (> 1.7.0)

### ISSUE THREAD

**Issue by kitao** [kitao/pyxel#574]
I tried compiling Pyxel with Maturin 1.7.1+.

I changed an option in Pyxel's makefile from `--skip-auditwheel` to `--auditwheel skip` and then the compilation finished.
But when run an application, the following error occurs:
```
    pyxel.init(300, 300, title="hoge")
    ^^^^^^^^^^
AttributeError: module 'pyxel' has no attribute 'init'
```

@messense
Is there any other setting I should change?

**Comment by messense** [comment]
Could you open an issue in `pyo3/maturin` so I don't forget this? I'll take a look later when I'm free.

**Comment by TomaSajt** [comment]
Should be fixed by https://github.com/kitao/pyxel/pull/583

**Comment by kitao** [comment]
Thanks a lot. You've been a big help!
