### ISSUE TITLE
Python 3.8 should be required instead of the currently listed 3.7

### ISSUE THREAD

**Issue by matthewniznik** [kitao/pyxel#227]
**Describe the bug**
When attempting to run my pyxel game with python 3.7, I had the following error which was fixed by upgrading to python 3.8:

```
  File "C:\Users\removed\Anaconda3\lib\site-packages\pyxel\__init__.py", line 10, in <module>
    from . import core  # type: ignore
  File "C:\Users\removed\Anaconda3\lib\site-packages\pyxel\core\__init__.py", line 42, in <module>
    _lib = _load_library()
  File "C:\Users\removed\Anaconda3\lib\site-packages\pyxel\core\__init__.py", line 36, in _load_library
    os.add_dll_directory(dll_dir)
AttributeError: module 'os' has no attribute 'add_dll_directory'
```

I think the documentation should be updated to require Python 3.8 (if backwards compatibility isn't an option)

**To Reproduce**
1. Run any module that imports pyxel with python 3.7
2. The error above appears

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by GitRenhl** [comment]
I removed this line https://github.com/kitao/pyxel/blob/46a9a7cff6e00603f480ab49393fe4f08b83d57a/pyxel/core/__init__.py#L36 which cause this error and now it works with python 3.7
¯\\_( ͡º ͜ʖ͡º)_/¯

**Comment by kitao** [comment]
Thank you for reporting!
I fixed this issue and Pyxel 3.8.1 should work on both Python 3.7 and 3.8.
